Repository Divyarajsinh1312/Django-CRUD, pull requests merged in 2022-10, with the labels that each got.

#1 Update main.html
  accounts/templates/accounts/main.html
Labels: hactoberfest

#2 Update main.html
  accounts/templates/accounts/main.html
Labels: hactoberfest, hacktoberfest-accepted

#3 add gitignore, rm cached files
  .gitignore
  __pycache__/manage.cpython-310.pyc
  accounts/__pycache__/__init__.cpython-310.pyc
  accounts/__pycache__/admin.cpython-310.pyc
  accounts/__pycache__/apps.cpython-310.pyc
  accounts/__pycache__/decorators.cpython-310.pyc
  accounts/__pycache__/forms.cpython-310.pyc
  accounts/__pycache__/models.cpython-310.pyc
  accounts/__pycache__/signals.cpython-310.pyc
  accounts/__pycache__/urls.cpython-310.pyc
  accounts/__pycache__/views.cpython-310.pyc
  crm/__pycache__/__init__.cpython-310.pyc
  crm/__pycache__/settings.cpython-310.pyc
  crm/__pycache__/urls.cpython-310.pyc
  crm/__pycache__/wsgi.cpython-310.pyc
Labels: hactoberfest, hactoberfest-accepted

#7 Update main.html
  accounts/templates/accounts/main.html
Labels: hactoberfest, hactoberfest-accepted

#10 Add files via upload
  server.py
Labels: hacktoberfest-accepted

#12 Add files via upload
  Vowl (1).java
Labels: hacktoberfest-accepted
